### 00 Tensor是什么
张量，描述任意物体复杂维度；    
标量，零维表格；     
向量，一维表格；    
矩阵，二维表格；    


机器学习；    
$ y = wx + b $      
w, b在未知时候，就是变量

样本 模型       
样本——Tensor；

tensor核心概念:     
类型——创建；            
属性——运算；
操作——Numpy的互相转换；

tensor的类型    
float32, float16, uint8, int8, int6, int32, int64, bool     

![img_Tensor的创建](img_Tensor的创建.png)

In [1]:
import torch
a = torch.Tensor([[1, 2], [3, 4]])
print(a)
print(a.type())


a = torch.Tensor(2, 3)
print(a)
print(a.type())

a = torch.ones(2, 3)
print(a)
print(a.type())

a = torch.eye(2, 3)
print(a)
print(a.type())

a = torch.zeros(2, 3)
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor
tensor([[-1.1344e-36,  7.3848e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.FloatTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor
tensor([[1., 0., 0.],
        [0., 1., 0.]])
torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [2]:
b = torch.Tensor(2, 3)
b = torch.zeros_like(b)
b = torch.ones_like(b)


print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [3]:
a = torch.rand(2, 2)
print(a)
print(a.type())

tensor([[0.1593, 0.8700],
        [0.6065, 0.9481]])
torch.FloatTensor


随机的生成一些满足一定分布的张量；      
正态分布，normal

In [4]:
torch.normal(mean=0.0, std=torch.rand(5))
print(a)
print(a.type())

tensor([[0.1593, 0.8700],
        [0.6065, 0.9481]])
torch.FloatTensor


In [5]:
torch.normal(mean=torch.rand(5), std=torch.rand(5))
print(a)
print(a.type())

tensor([[0.1593, 0.8700],
        [0.6065, 0.9481]])
torch.FloatTensor


随机生成均匀分布的数值uniform_()

In [6]:
a = torch.Tensor(2, 2).uniform_(-1, 1)
print(a)
print(a.type())

tensor([[-0.3392,  0.3145],
        [-0.3022,  0.4031]])
torch.FloatTensor


生成一些序列数

In [7]:
a = torch.arange(0, 10, 1)
print(a)
print(a.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


生成等间隔的n个数字

In [8]:
a = torch.linspace(2, 10, 3)
print(a)
print(a.type())

tensor([ 2.,  6., 10.])
torch.FloatTensor


In [9]:
a = torch.randperm(10)
print(a)
print(a.type())

tensor([0, 9, 2, 3, 1, 8, 4, 7, 5, 6])
torch.LongTensor


对比numpy 和tensor

In [10]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


### 01 Tensor的属性

每一个Tensor有torch.dtype, torch.device, torch.layout三种属性           
+ torch.device标识了torch.Tensor对象在创建之后所存储在的设备的名称        
+ torch.layout表示torch.Tensor内存布局的对象(稠密张量或者稀疏张量，稠密张量一般直接存在内存中的连续区域，稀疏张量只存储其非零坐标)        
+ torch.tensor([1,2,3], dtype=torch.float32, device = torch.device('cpu'))

稀疏张量的定义方式          
torch.sparse_coo_tensor
coo类型表示了非零元素的坐标形式     
x = torch.sparse_coo_tensor(i, v, [2, 4])       
稀疏与低秩      
+ 稀疏描述了一个张量中的非零元素的多少        
+ 秩表示了当前张量中的线性可表示关系      

In [11]:
import torch

dev = torch.device('cpu')
dev = torch.device('cuda')

In [12]:
a = torch.tensor([2, 2], 
                 dtype=torch.float32,
                 device=dev)
print(a)
print(a.device)

tensor([2., 2.], device='cuda:0')
cuda:0


In [13]:
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
v = torch.tensor([1, 2, 3])
a = torch.sparse_coo_tensor(i, v, (4, 4),
                                   dtype=torch.float32,
                                      device=dev).to_dense()
print(a)

tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='cuda:0')


### 02 Tensor的算术运算

加法运算        
c = a + b   
c = torch.add(a, b)     
a.add(b)        
a.add_(b)       

In [14]:
import torch

a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

print(a + b)
print(a.add(b))
print(torch.add(a, b))
print(a)
print(a.add_(b))
print(a)

tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[0.6249, 0.7071, 0.0352],
        [0.7800, 0.2171, 0.4086]])
tensor([[1.4099, 1.5856, 0.1547],
        [1.2402, 1.1627, 0.6898]])
tensor([[1.4099, 1.5856, 0.1547],
        [1.2402, 1.1627, 0.6898]])
tensor([[1.4099, 1.5856, 0.1547],
        [1.2402, 1.1627, 0.6898]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[1.4099, 1.5856, 0.1547],
        [1.2402, 1.1627, 0.6898]])
tensor([[1.4099, 1.5856, 0.1547],
        [1.2402, 1.1627, 0.6898]])


减法运算        
c = a - b       
c = torch.sub(a, b)     
a.sub(b)        
a.sub_(b)       

In [15]:
print(a - b)
print(a.sub(b))
print(torch.sub(a, b))
print(a)
print(a.sub_(b))

tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[1.4099, 1.5856, 0.1547],
        [1.2402, 1.1627, 0.6898]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])


乘法运算        
+ 哈达玛积（element wise, 对应元素相乘）！注意与矩阵运算不同！      

c = a * b   
c = torch.mul(a, b)     
a.mul(b)        
a.mul_(b)       

In [16]:
print(a * b)
print(torch.mul(a, b))
print(a.mul(b))
print(a)
print(a.mul_(b))

tensor([[0.4905, 0.6212, 0.0042],
        [0.3590, 0.2053, 0.1149]])
tensor([[0.4905, 0.6212, 0.0042],
        [0.3590, 0.2053, 0.1149]])
tensor([[0.4905, 0.6212, 0.0042],
        [0.3590, 0.2053, 0.1149]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[0.4905, 0.6212, 0.0042],
        [0.3590, 0.2053, 0.1149]])


除法运算        
c = a/b     
c = torch.div(a, b)     
a.div(b)        
a.div_(b)

In [17]:
print(a / b)
print(torch.div(a, b))
print(a.div(b))
print(a)
print(a.div_(b))

tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])
tensor([[0.4905, 0.6212, 0.0042],
        [0.3590, 0.2053, 0.1149]])
tensor([[0.7850, 0.8786, 0.1194],
        [0.4603, 0.9456, 0.2812]])


矩阵运算        
+ 二维矩阵乘法运算操作包括torch.mm()、torch.matmul()、@     

    a = torch.ones(2, 1)        
    b = torch.ones(1, 2)        
    print(torch.mm(a, b))       
    print(torch.matmul(a, b))       
    print(a @ b)        
    print(a.matmul(b))      
    print(a.mm(b))      


    a x b的矩阵必须要保证a是m乘n，b是n乘P   

+ 对于高维的Tensor(dim > 2)，定义其矩阵乘法仅在最后的两个维度上，       
要求前面的维度必须保持一致，就像矩阵的索引一样并且运算操只有torch.matmul()

    a = torch.ones(1, 2, 3, 4)      
    b = torch.ones(1, 2, 4, 4)      
    print(a.matmul(b))      
    print(torch.matmul(a, b))       

In [18]:
a = torch.ones(2, 1)        
b = torch.ones(1, 2)        
print(a)
print(b)
print("_______________")
print(a @ b)
print(a.matmul(b))
print(torch.matmul(a, b))
print(torch.mm(a, b))
print(a.mm(b))

tensor([[1.],
        [1.]])
tensor([[1., 1.]])
_______________
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [19]:
a = torch.ones(1, 2, 3, 4)
b = torch.ones(1, 2, 4, 3)


print(a.matmul(b))
print("**************************")
print(a.matmul(b).shape)

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
**************************
torch.Size([1, 2, 3, 3])


幂运算      

print(torch.pow(a, 2))      
print(a.pow(2))     
print(a**2)     
print(a.pow_(2))        

In [20]:
a = torch.tensor([1, 2])
print(torch.pow(a, 3))
print(a.pow(3))
print(a**3)
print(a.pow_(3))
print(a)

tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])


e的n次方

print(torch.exp(a))     
b = a.exp_()        

In [21]:
a = torch.tensor([1.0, 2.0])
print(torch.exp(a))
print(torch.exp_(a))
print(a.exp())
print(a.exp_())


tensor([2.7183, 7.3891])
tensor([2.7183, 7.3891])
tensor([  15.1543, 1618.1782])
tensor([  15.1543, 1618.1782])


开方运算        

print(a.sqrt())     
print(a.sqrt_())        
print(a)        

In [22]:
a = torch.tensor([10.0, 2.0])
print(a)
print(torch.sqrt(a))
print(torch.sqrt_(a))
print(a)
print(a.sqrt())
print(a.sqrt_())

tensor([10.,  2.])
tensor([3.1623, 1.4142])
tensor([3.1623, 1.4142])
tensor([3.1623, 1.4142])
tensor([1.7783, 1.1892])
tensor([1.7783, 1.1892])


对数运算        

print(torch.log2(a))        
print(torch.log10(a))       
print(torch.log(a))     
print(torch.log_(a))        

In [23]:
a = torch.tensor([10.0, 2.0])
print(torch.log(a))
print(torch.log_(a))
print(a.log())
print(a.log_())

tensor([2.3026, 0.6931])
tensor([2.3026, 0.6931])
tensor([ 0.8340, -0.3665])
tensor([ 0.8340, -0.3665])


### 03 Pytorch中的in-place操作

+ “就地”操作，即不允许使用临时变量。          
+ 也称为原位操作。        
+ x = x + y       
+ add_，sub_, mul_等等        

### 04 广播机制
+ 广播机制：张量参数可以自动扩展为相同大小（类似于Numpy)
+ 广播机制需要满足两个条件：
    - 每个张量至少有一个维度
    - 满足右对齐
    - torch.rand(2, 1, 1)+torch.rand(3)

In [24]:
import torch
a = torch.rand(2, 3)
b = torch.rand(3)

print(a)
print(b)
print(a + b)

tensor([[0.7309, 0.4898, 0.6813],
        [0.7110, 0.8748, 0.5183]])
tensor([0.6480, 0.0669, 0.8442])
tensor([[1.3789, 0.5568, 1.5255],
        [1.3590, 0.9417, 1.3624]])


05 取整和取余运算

In [25]:
import torch

a = torch.rand(2, 2)
a = a * 10
print(a)

print(torch.floor(a))
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))
print(torch.frac(a))
print(a % 2)


tensor([[5.5960, 8.5302],
        [4.4176, 4.8341]])
tensor([[5., 8.],
        [4., 4.]])
tensor([[6., 9.],
        [5., 5.]])
tensor([[6., 9.],
        [4., 5.]])
tensor([[5., 8.],
        [4., 4.]])
tensor([[0.5960, 0.5302],
        [0.4176, 0.8341]])
tensor([[1.5960, 0.5302],
        [0.4176, 0.8341]])


### 05 比较运算

torch.eq(input, other, out=None) # 按成员进行等式操作，相同返回True     
torch.equal(tensor1, tensor2) # 判断两个张量是否有相同的size 和 elements，则为True      
torch.ge(input, other, out=None) # 按成员进行大于等于操作，大于等于返回True     
torch.gt(input, other, out=None) # 按成员进行大于操作，大于返回True     
torch.le(input, other, out=None) # 按成员进行小于等于操作，小于等于返回True     
torch.lt(input, other, out=None) # 按成员进行小于操作，小于返回True     
torch.ne(input, other, out=None) # 按成员进行不等式操作，不相同返回True     




In [26]:
import torch

a = torch.rand(2, 3)
b = torch.rand(2, 3)


print(a)
print(b)

print(torch.eq(a, b))
print(torch.equal(a, b))
print(torch.ge(a, b))
print(torch.gt(a, b))
print(torch.le(a, b))
print(torch.lt(a, b))
print(torch.ne(a, b))



tensor([[0.4737, 0.9322, 0.8486],
        [0.5744, 0.6898, 0.4550]])
tensor([[0.7290, 0.8597, 0.0208],
        [0.9196, 0.5409, 0.3582]])
tensor([[False, False, False],
        [False, False, False]])
False
tensor([[False,  True,  True],
        [False,  True,  True]])
tensor([[False,  True,  True],
        [False,  True,  True]])
tensor([[ True, False, False],
        [ True, False, False]])
tensor([[ True, False, False],
        [ True, False, False]])
tensor([[True, True, True],
        [True, True, True]])


### 06 取前k大/前k小/第k小的数值及其索引

+ torch.sort(input, dim=None, descending = False, out=None) #对目标张量input沿着指定维按升序排序      
+ torch.topk(input, k, dim=None, largest=True, sorted=True, out=None) #沿着指定维度返回最大k个数值及其索引值      
    这个一般用在深度学习中对loss函数进行定义时候            
+ torch.kthvalue(input, k, dim=None, keepdim=False, out=None) #沿着指定维度返回第k个最小值及其索引值      

In [27]:
a = torch.tensor([1, 4, 4, 3, 5])
print(torch.sort(a))

torch.return_types.sort(
values=tensor([1, 3, 4, 4, 5]),
indices=tensor([0, 3, 1, 2, 4]))


In [28]:
a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
print(a.shape)
print(torch.sort(a, dim = 1, descending=True))

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[5, 4, 4, 3, 1],
        [5, 3, 3, 2, 1]]),
indices=tensor([[4, 1, 2, 3, 0],
        [4, 1, 3, 0, 2]]))


In [29]:
##topk
a = torch.tensor([[2, 4, 3, 1,5],
                  [2, 3, 5, 1, 4]])
print(a.shape)

print(torch.topk(a, k = 2, dim=0))
print(torch.topk(a, k = 1, dim=0))
print(torch.topk(a, k = 1, dim=1))
print(torch.topk(a, k = 2, dim=1))


torch.Size([2, 5])
torch.return_types.topk(
values=tensor([[2, 4, 5, 1, 5],
        [2, 3, 3, 1, 4]]),
indices=tensor([[0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1]]))
torch.return_types.topk(
values=tensor([[2, 4, 5, 1, 5]]),
indices=tensor([[0, 0, 1, 0, 0]]))
torch.return_types.topk(
values=tensor([[5],
        [5]]),
indices=tensor([[4],
        [2]]))
torch.return_types.topk(
values=tensor([[5, 4],
        [5, 4]]),
indices=tensor([[4, 1],
        [2, 4]]))


In [30]:
print(torch.kthvalue(a, k = 2, dim=0))
print(torch.kthvalue(a, k = 2, dim=1))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))
torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


### 07 判断是否为finite/inf/nan

+ torch.isfinite(tensor)/torch.isinf(tensor)/torch.isnan(tensor)      
+ 返回一个标记元素是否为finite/inf/nan的mask张量      

In [31]:
a = torch.rand(2, 3)

print(a)
print(a/0)
print(torch.isfinite(a))
print(torch.isfinite(a/0))
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[0.9986, 0.8089, 0.1919],
        [0.0518, 0.0589, 0.2405]])
tensor([[inf, inf, inf],
        [inf, inf, inf]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [32]:
import numpy as np

a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))
print(torch.isinf(a))


tensor([False, False,  True])
tensor([False, False, False])


### 08 三角函数

torch.abs(input, out=None)      
torch.acos(input, out=None)     
torch.asin(input, out=None)     
torch.atan(input, out=None)     
torch.atan2(input1, input2, out=None)       
torch.cos(input, out=None)      
torch.cosh(input, out=None)     
torch.sin(input, out=None)      
torch.sinh(input, out=None)     
torch.tan(input, out=None)      
torch.tanh(input, out=None)     


In [33]:
import torch
a = torch.rand(2, 3)
print(a)
b = torch.cos(a)
print(b)

tensor([[0.3427, 0.0664, 0.6329],
        [0.8589, 0.6158, 0.2462]])
tensor([[0.9419, 0.9978, 0.8063],
        [0.6533, 0.8163, 0.9698]])


### 09 其它的数学函数

torch.asb()     
torch.erf()     
torch.erfinv()      
torch.sigmoid()     
torch.neg()     
torch.reciprocal()      
torch.rsqrt()       
torch.sign()        
torch.lerp()        
torch.addcdiv()     
torch.addcmul()     
torch.cumprod()     
torch.cumsum()      

### 10 统计学有关的函数

torch.mean()   #平均值      
torch.sum()    #求和            
torch.prod()   #求积            
torch.max()    #最大值      
torch.min()    #最小值      
torch.argmax() #最大值索引      
torch.argmin() #最小值索引      


torch.median() #中位数      
torch.std()    #标准差      
torch.var()    #方差        
torch.mode()   #众数        
torch.histc()  #直方图统计      
torch.bincount() #计数      

In [34]:
import torch

a = torch.rand(2, 2)

print(a)
print(torch.mean(a))
print(torch.sum(a))
print(torch.prod(a))
print(torch.std(a))
print(torch.var(a))
print(torch.median(a))
print(torch.mode(a))
print(torch.norm(a))
print(torch.dist(a, a))
print(torch.histc(a))

tensor([[0.7996, 0.4317],
        [0.7420, 0.8674]])
tensor(0.7102)
tensor(2.8408)
tensor(0.2222)
tensor(0.1926)
tensor(0.0371)
tensor(0.7420)
torch.return_types.mode(
values=tensor([0.4317, 0.7420]),
indices=tensor([1, 0]))
tensor(1.4590)
tensor(0.)
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])


In [35]:
a = torch.rand(2, 2) * 10
print(a)

print(torch.histc(a, bins=4, min=0, max=10))

tensor([[5.1951, 1.0260],
        [0.2502, 7.0497]])
tensor([2., 0., 2., 0.])


### 11 分布函数torch.distributions

如机器学习中的训练集和测试集的分布是否一致      

- distributions包含可参数化的概率分布和采样函数             
    - 得分函数           
         - 强化学习中策略梯度方法的基础               
    - pathwise derivative估计器       
        - 变分自动编码器中的重新参数化技巧        

### 12 随机抽样函数

- 定义随机种子          
    - torch.manual_seed(seed)       
- 定义随机满足的分布        
    - torch.normal()

In [36]:
import torch

torch.manual_seed(42)
mean = torch.rand(1, 2)
std  = torch.rand(1, 2)

print(torch.normal(mean, std))

tensor([[0.9720, 1.1360]])


- 范数
    - 在泛函分析中，它定义在赋范线性空间中，并满足一定的条件，即1.非负性；2齐次性；3.三角不等式
    - 常被用来度量某个向量空间（或矩阵）中的每个向量的长度或大小

- 0范数/1范数/2范数/p范数/核范数
    - torch.dist(input, other, p=2)计算p范数
    - torch.norm() 计算2范数

### 补：向量与矩阵的范数

范数（Norm）是一个数学概念，表示向量或矩阵的“大小”或“长度”，        
它是衡量向量或矩阵在空间中某种距离的方式。在数学、物理学和计算机科学中，        
范数常用于优化、距离计算、机器学习和信号处理等领域。

以下是几种常见的范数：0范数、1范数、2范数、p范数、核范数，      
它们通常用于向量和矩阵的计算中，不同的范数具有不同的特性和应用。        

---

#### 1. 0 范数（零范数，L0 Norm）       
**定义**：零范数并不是真正的范数，但它常常被用来计算一个向量或矩阵中非零元素的个数。        
用公式表示为：      
$ \|x\|_0 = \text{非零元素的个数} $

**性质**：
- 零范数不是严格意义上的范数，因为它不满足**齐次性**（例如，$ \| \alpha x \|_0 \neq \alpha \| x \|_0 $，对于标量 $ \alpha $）。
- 但是，零范数通常用于**稀疏性**相关的任务中，比如 **LASSO回归**、**特征选择**等。

**应用**：
- **稀疏表示**：通过零范数可以衡量一个向量或矩阵有多少个非零元素。      
在机器学习中，通常希望得到一个具有较少非零元素的模型，这样的模型更加稀疏、简单、易于解释。      
- **特征选择**：通过零范数来选出最重要的特征，抑制不重要的特征。

---

#### 2. 1 范数（L1 Norm）
**定义**：1范数是向量中所有元素绝对值的和，公式如下：
$ \|x\|_1 = \sum_i |x_i| $

**性质**：
- L1 范数会使得一些元素变为 0，因此常用于实现**稀疏化**。
- 它对于噪声较敏感，但能够很好地处理**稀疏问题**。

**应用**：
- **LASSO回归**：L1范数用于正则化（惩罚模型的复杂度），     
通过约束模型参数的 L1 范数来使得一些系数变为 0，从而选择重要特征。      
- **稀疏编码和压缩感知**：L1范数用于找到稀疏表示，减少数据的冗余。      
  
---

#### 3. 2 范数（L2 Norm）
**定义**：2范数，也称为 **欧几里得范数**，是向量各元素的平方和的平方根，公式如下：
$ \|x\|_2 = \sqrt{\sum_i x_i^2} $

**性质**：
- L2 范数与欧几里得距离相关，常用于计算两点之间的距离。
- L2 范数的优点是其具有**平滑性**，不会导致像 L1 范数那样产生稀疏解。
- L2 范数对于异常值更为**鲁棒**，相比 L1 范数，它的计算结果更为平滑。

**应用**：
- **Ridge回归**：L2范数用于正则化，通过约束参数的L2范数来控制模型的复杂度，避免过拟合。
- **梯度下降算法**：L2范数常用于优化问题中，特别是当我们需要最小化误差平方和时。

---

#### 4. p 范数（Lp Norm）
**定义**：p范数是对任意 $p \geq 1$ 的扩展，公式如下：
$ \|x\|_p = \left( \sum_i |x_i|^p \right)^{1/p} $       
当 $p = 1$ 时，得到的是 **L1范数**，当 $p = 2$ 时，得到的是 **L2范数**，        
当 $p \to \infty$ 时，得到的是 **最大值范数**（即最大元素的绝对值）。       

**性质**：
- 当 $p = 1$，是 L1 范数；
- 当 $p = 2$，是 L2 范数；
- 随着 $p$ 增加，p 范数变得对大元素更敏感，尤其是 $p$ 较大时，p 范数更加注重向量中最大元素的影响。

**应用**：
- **正则化**：p范数的正则化（例如，L1正则化和L2正则化）用于约束模型的参数，防止过拟合。
- **最优解的选择**：在机器学习中，根据问题需要选择不同的 p 范数进行优化，p 范数适用于不同的平滑性需求。

---

#### 5. 核范数（Nuclear Norm）
**定义**：核范数是一个矩阵的所有奇异值的和，也可以理解为矩阵的 **L1 范数** 对奇异值的扩展。     
对于矩阵 $X$，其核范数定义为：      
$ \|X\|_* = \sum_i \sigma_i $       
其中 $ \sigma_i $ 是矩阵 $X$ 的奇异值。     

**性质**：
- 核范数广泛用于矩阵补全问题中，能够得到**低秩矩阵**。
- 核范数与 **L1 范数** 类似，但它作用于矩阵的奇异值，而不是矩阵元素本身。
  
**应用**：
- **矩阵补全**：在缺失数据的情况下，使用核范数来逼近低秩矩阵，常用于推荐系统（如Netflix的电影推荐）。
- **低秩矩阵恢复**：核范数正则化能够找到矩阵的低秩近似，广泛应用于图像去噪、信号恢复、协同过滤等领域。

---

#### 总结

| **范数**   | **定义**                                         | **性质**                                         | **常见应用**                                           |
|------------|--------------------------------------------------|--------------------------------------------------|--------------------------------------------------------|
| **0范数**  | 非零元素的个数                                   | 不满足常规范数条件，常用于稀疏性                  | 特征选择，稀疏编码                                    |
| **1范数**  | 向量元素绝对值之和                               | 对稀疏性友好，可使部分元素为零                    | LASSO回归，稀疏编码，压缩感知                        |
| **2范数**  | 向量元素平方和的平方根                           | 对异常值更为鲁棒，平滑                            | Ridge回归，机器学习中的常见损失函数，距离计算        |
| **p范数**  | 向量元素绝对值的p次方和的p次方根                 | 对大元素更敏感，p越大对极值越敏感                 | 最优化问题，正则化，调整平滑性                        |
| **核范数** | 矩阵奇异值的和                                   | 用于低秩矩阵恢复，矩阵补全                        | 矩阵补全，推荐系统，低秩矩阵恢复                      |

这些范数在 **机器学习、深度学习、信号处理** 和 **图像处理** 等多个领域有着广泛的应用，能够帮助我们在优化模型时控制参数的大小或稀疏性，解决实际问题中的多种挑战。


In [37]:
import torch

a = torch.rand(2, 1)
b = torch.rand(2, 1)

print(a, b)
print(torch.dist(a, b, p = 1 ))
print(torch.dist(a, b, p = 2 ))
print(torch.dist(a, b, p = 3 ))


print(torch.norm(a))

tensor([[0.9408],
        [0.1332]]) tensor([[0.9346],
        [0.5936]])
tensor(0.4666)
tensor(0.4604)
tensor(0.4604)
tensor(0.9502)


### 13 矩阵分解

- 常见的矩阵分解
    - LU分解：将矩阵A分解为L（下三角）矩阵和U（上三角）矩阵的乘积       
    - QR分解：将原矩阵分解为一个正交矩阵Q和一个上三角矩阵R的乘积        
    - EVD分解：特征值分解  PCA      
    - SVD分解：奇异值分解  LDA      

- 特征值分解
    - 将矩阵分解为由其特征值和特征向量表示的矩阵之积的方法
    - 特征值 VS 特征向量     

            $ A \mathbf{v} = \lambda \mathbf{v} $       
            $ A = Q \Sigma Q^{-1} $

- PCA与特征值分解
    - PCA：将n维特征映射到k维上，这k维是全新的正交特征也被称为主成分，是在原有n维特征的基础上重新构造出来的k维特征
    - PCA算法的优化目标是“
        - 降维后同一维度的方差最大
        - 不同维度之间的相关性为0
        - 协方差矩阵

### 14 矩阵分解-SVD分解

- 奇异值分解，即SVD分解

$$ A = U \Sigma V^T $$


- LDA与奇异值分解       
- EVD分解 VS SVD分解        
    - 矩阵方阵且满秩（可对角化）        
    - 矩阵分解不等于特征降维度      
    - 协防长矩阵描述方差喝相关性        

- Pytorch中的奇异值分解
    - torch.svd()

### 15 Tensor的裁剪运算

- 对Tensor中的元素范围进行过滤      
- 常用于梯度裁剪（gradient clipping），即在发生梯度离散或者梯度爆炸时对梯度的处理       
- a.clamp(2, 10)

In [3]:
import torch

a = torch.rand(2, 2) * 10
print(a)

a = a.clamp(2, 5)
print(a)

tensor([[2.3723, 2.4819],
        [7.2736, 0.4597]])
tensor([[2.3723, 2.4819],
        [5.0000, 2.0000]])


### 16 张量的索引与数据筛选

- torch.where(condition, x, y): 按照条件从x和y中选满足条件的元素组成新的tensor      
- torch.gather(input, dim, index, out=None)：在指定维度上按照索引赋值输出tensor     
- torch.index_select(input, dim, index, out=None)：按照指定索引输出tensor       
- torch.masked_select(input, mask, out=None)：按照mask输出tensor，输出为向量        
- torch.take(input, indices)：将输入看成1D-tensor，按照索引得到输出tensor       
- torch.nonzero(input， out=None)：输出非0元素的坐标        

In [4]:
import torch
# Where
a = torch.rand(4, 4)
b = torch.rand(4, 4)

print(a)
print(b)

out = torch.where(a > 0.5, a, b)
print(out)


tensor([[0.6033, 0.5812, 0.2200, 0.4279],
        [0.5222, 0.2453, 0.4955, 0.6322],
        [0.1450, 0.9558, 0.6763, 0.0885],
        [0.7301, 0.8784, 0.3074, 0.4570]])
tensor([[0.2586, 0.1397, 0.0736, 0.6076],
        [0.0181, 0.1982, 0.1275, 0.4236],
        [0.1943, 0.3333, 0.6483, 0.5913],
        [0.4964, 0.4235, 0.7366, 0.0802]])
tensor([[0.6033, 0.5812, 0.0736, 0.6076],
        [0.5222, 0.1982, 0.1275, 0.6322],
        [0.1943, 0.9558, 0.6763, 0.5913],
        [0.7301, 0.8784, 0.7366, 0.0802]])


In [5]:
# torch.index_select

a = torch.rand(4, 4)
print(a)
b = torch.index_select(a, dim=0, index = torch.tensor([0, 3, 2]))
print(b)

tensor([[0.3414, 0.2330, 0.3823, 0.5255],
        [0.8645, 0.0057, 0.6850, 0.6673],
        [0.0357, 0.9737, 0.2243, 0.4482],
        [0.6749, 0.7086, 0.7671, 0.2800]])
tensor([[0.3414, 0.2330, 0.3823, 0.5255],
        [0.6749, 0.7086, 0.7671, 0.2800],
        [0.0357, 0.9737, 0.2243, 0.4482]])


In [7]:
# torch.gather

a = torch.linspace(1, 16, 16).view(4, 4)

print(a)

out = torch.gather(a, dim=0, index=torch.tensor([[0, 1, 1, 1],
                                           [0, 1, 2, 2],
                                           [0, 1, 3, 3]]))

print(out)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])


In [ ]:
#  torch.masked_select
a = torch.linspace(1, 16, 16).view(4, 4)
print(a)
mask = torch.gt(a, 8)
print(mask)
out = torch.masked_select(a, mask)
print(out)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])


In [9]:
# torch.take

a = torch.linspace(1, 16, 16).view(4, 4)
print(a)

out = torch.take(a, torch.tensor([0, 5, 10, 15]))
print(out)


tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([ 1.,  6., 11., 16.])


In [10]:
# torch.nonzero

a = torch.tensor([[0, 1, 2, 0],
                  [2, 3, 0, 1]])
print(a)
out = torch.nonzero(a)
print(out)

tensor([[0, 1, 2, 0],
        [2, 3, 0, 1]])
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])


### 17 张量的组合与拼接

- torch.cat(seq, dim=0, out=None)：按照已经存在的维度进行拼接       
- torch.stack(seq, dim=0, out=None)：按照新的维度进行拼接       
- torch.gather(input,dim,index,out=None)：在指定维度上按照索引赋值输出tensor        

In [13]:
import torch

a = torch.zeros((2, 4))
b = torch.ones((2, 4))
print(a)
print(b)

out = torch.cat((a, b), dim=0)
print(out)

out = torch.cat((a, b), dim=1)
print(out)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])


In [15]:
# stack

a  = torch.linspace(1, 6, 6).view(2, 3)
b  = torch.linspace(7, 12, 6).view(2, 3)

print(a)
print(b)

out = torch.stack((a, b), dim=0)
print(out)

out = torch.stack((a, b), dim=1)
print(out)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])


### 18 张量的切片

- torch.chunk(tensor, chunks, dim=0) 按照某个维度平均分块（最后一个可能小于平均值）     
- torch.split(tensor, split_size_or_sections, dim=0) 按照某个维度依照第二个参数给出的list或者int进行分割tensor      

In [17]:
import torch

a = torch.rand((3, 4))

print(a)
out = torch.chunk(a, 2, dim=1)
print(out[0], out[0].shape)
print(out[1], out[1].shape)

tensor([[0.6562, 0.3315, 0.3690, 0.6879],
        [0.1346, 0.2862, 0.9711, 0.8135],
        [0.3375, 0.7985, 0.5453, 0.8104]])
tensor([[0.6562, 0.3315],
        [0.1346, 0.2862],
        [0.3375, 0.7985]]) torch.Size([3, 2])
tensor([[0.3690, 0.6879],
        [0.9711, 0.8135],
        [0.5453, 0.8104]]) torch.Size([3, 2])


In [21]:
out = torch.split(a, 3, dim=0)
print(out)

(tensor([[0.6562, 0.3315, 0.3690, 0.6879],
        [0.1346, 0.2862, 0.9711, 0.8135],
        [0.3375, 0.7985, 0.5453, 0.8104]]),)


### 19 张量变形

- torch.reshape(input, shape)       
- torch.t(input)： 只针对2D tensor转置      
- torch.transpose(input, dim0, dim1)：交换两个维度      
- torch.squeeze(input, dim = None, out = None)：去除那些维度大小为1的维度       
- torch.unbind(tensor, dim=0): 去除某个维度     
- torch.unsqueeze(input, dim, out=None)：在指定位置添加维度     
- torch.flip(input, dims)：按照给定维度翻转张量     
- torch.rot90(input, k, dims)：按照指定维度和旋转次数进行张量旋转       

In [1]:
import torch

a = torch.rand(2, 3)

print(a)
out = torch.reshape(a, (3, 2))
print(out)


tensor([[0.1457, 0.8102, 0.7798],
        [0.6540, 0.7154, 0.2918]])
tensor([[0.1457, 0.8102],
        [0.7798, 0.6540],
        [0.7154, 0.2918]])


In [2]:
torch.t(out)

tensor([[0.1457, 0.7798, 0.7154],
        [0.8102, 0.6540, 0.2918]])

In [3]:
torch.transpose(out, 0, 1)

tensor([[0.1457, 0.7798, 0.7154],
        [0.8102, 0.6540, 0.2918]])

In [4]:
a = torch.rand(1, 2, 3)
print(torch.transpose(a, 0, 1))
print(torch.transpose(a, 0, 1).shape)

tensor([[[0.7486, 0.1014, 0.3502]],

        [[0.4669, 0.5676, 0.7732]]])
torch.Size([2, 1, 3])


### 20 张量的填充

- 定义Tensor, 并填充指定的数值      
    - torch.full((2, 3), 3.14)
        - tensor([[3.14, 3.14, 3.14], [3.14, 3.14, 3.14]])      

- 频谱操作      
    - torch.fft等

### 21 Pytorch的其它技巧

- 模型的保存/加载
    - torch.saves(state, dir)     保存/序列化   
    - torch.load(dir)   加载模型        

- 并行化        
    - torch.get_num_threads():      
        - 获得用于并行化CPU操作的OpenMP线程数   
    - torch.set_num_threads(int)：      
        - 设定用于并行化CPU操作的OpenMP线程数

- 分布式
    - Python默认只使用一个GPU，在多个GPU的情况下就需要使用Pytorch提供的DataParallel     
    - 单机多卡      
    - 多机多卡      

- Tensor on GPU
- 一般进行数据处理时候放CPU上，进行模型操作时候放GPU上；        
- 用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动      
- 如下示例代码：        

if torch.cuda.is_available():
        device = torch.device("cuda")       #GPU        
        y = torch.ones_like(x, device=device) # 直接创建一个在GPU上的Tensor       
        x = x.to(device)          
        z = x + y       
        print(z)        
        print(z.to("cpu", torch.double))    # to()还可以同时更改数据类型        


- Tensor的相关配置

    - torch.is tensor()#如果是pytorch的tensor类型返回true   
    - torch.is storage()#如果是pytorch的storage类型返回ture     
    - torch.set flush denormal(mode)#防止一些不正常的元素产生       
    - torch.set default dtype(d)#对torch.tensor()设置默认的浮点类型     
    - torch.set printoptions(precision=None, threshold=None,edgeitems=None,     
        linewidth=None, profile=None)# 设置printing的打印参数       
    - 等等

- Tensor与Numpy的互相转换

    - torch.from_numpy(ndarry)      
    - a.numpy()     