### 00 Tensor是什么
张量，描述任意物体复杂维度；    
标量，零维表格；     
向量，一维表格；    
矩阵，二维表格；    


机器学习；    
$ y = wx + b $      
w, b在未知时候，就是变量

样本 模型       
样本——Tensor；

tensor核心概念:     
类型——创建；            
属性——运算；
操作——Numpy的互相转换；

tensor的类型    
float32, float16, uint8, int8, int6, int32, int64, bool     

![img_Tensor的创建](img_Tensor的创建.png)

In [9]:
import torch
a = torch.Tensor([[1, 2], [3, 4]])
print(a)
print(a.type())


a = torch.Tensor(2, 3)
print(a)
print(a.type())

a = torch.ones(2, 3)
print(a)
print(a.type())

a = torch.eye(2, 3)
print(a)
print(a.type())

a = torch.zeros(2, 3)
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor
tensor([[1., 0., 0.],
        [0., 1., 0.]])
torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [11]:
b = torch.Tensor(2, 3)
b = torch.zeros_like(b)
b = torch.ones_like(b)


print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
a = torch.rand(2, 2)
print(a)
print(a.type())

tensor([[0.2340, 0.9680],
        [0.2138, 0.0225]])
torch.FloatTensor


随机的生成一些满足一定分布的张量；      
正态分布，normal

In [13]:
torch.normal(mean=0.0, std=torch.rand(5))
print(a)
print(a.type())

tensor([[0.2340, 0.9680],
        [0.2138, 0.0225]])
torch.FloatTensor


In [14]:
torch.normal(mean=torch.rand(5), std=torch.rand(5))
print(a)
print(a.type())

tensor([[0.2340, 0.9680],
        [0.2138, 0.0225]])
torch.FloatTensor


随机生成均匀分布的数值uniform_()

In [15]:
a = torch.Tensor(2, 2).uniform_(-1, 1)
print(a)
print(a.type())

tensor([[-0.8303,  0.6408],
        [-0.9712, -0.6875]])
torch.FloatTensor


生成一些序列数

In [16]:
a = torch.arange(0, 10, 1)
print(a)
print(a.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


生成等间隔的n个数字

In [19]:
a = torch.linspace(2, 10, 3)
print(a)
print(a.type())

tensor([ 2.,  6., 10.])
torch.FloatTensor


In [20]:
a = torch.randperm(10)
print(a)
print(a.type())

tensor([7, 4, 8, 9, 2, 3, 6, 0, 5, 1])
torch.LongTensor


对比numpy 和tensor

In [23]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


### 01 Tensor的属性

每一个Tensor有torch.dtype, torch.device, torch.layout三种属性           
+ torch.device标识了torch.Tensor对象在创建之后所存储在的设备的名称        
+ torch.layout表示torch.Tensor内存布局的对象(稠密张量或者稀疏张量，稠密张量一般直接存在内存中的连续区域，稀疏张量只存储其非零坐标)        
+ torch.tensor([1,2,3], dtype=torch.float32, device = torch.device('cpu'))

稀疏张量的定义方式          
torch.sparse_coo_tensor
coo类型表示了非零元素的坐标形式     
x = torch.sparse_coo_tensor(i, v, [2, 4])       
稀疏与低秩      
+ 稀疏描述了一个张量中的非零元素的多少        
+ 秩表示了当前张量中的线性可表示关系      

In [27]:
import torch

dev = torch.device('cpu')
dev = torch.device('cuda')

In [30]:
a = torch.tensor([2, 2], 
                 dtype=torch.float32,
                 device=dev)
print(a)
print(a.device)

tensor([2., 2.], device='cuda:0')
cuda:0


In [34]:
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
v = torch.tensor([1, 2, 3])
a = torch.sparse_coo_tensor(i, v, (4, 4),
                                   dtype=torch.float32,
                                      device=dev).to_dense()
print(a)

tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='cuda:0')


### 02 Tensor的算术运算

加法运算        
c = a + b   
c = torch.add(a, b)     
a.add(b)        
a.add_(b)       

In [35]:
import torch

a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

print(a + b)
print(a.add(b))
print(torch.add(a, b))
print(a)
print(a.add_(b))
print(a)

tensor([[0.9102, 0.8461, 0.9555],
        [0.7291, 0.0159, 0.0827]])
tensor([[0.7974, 0.7807, 0.9750],
        [0.2606, 0.5709, 0.2451]])
tensor([[1.7076, 1.6269, 1.9305],
        [0.9897, 0.5869, 0.3278]])
tensor([[1.7076, 1.6269, 1.9305],
        [0.9897, 0.5869, 0.3278]])
tensor([[1.7076, 1.6269, 1.9305],
        [0.9897, 0.5869, 0.3278]])
tensor([[0.9102, 0.8461, 0.9555],
        [0.7291, 0.0159, 0.0827]])
tensor([[1.7076, 1.6269, 1.9305],
        [0.9897, 0.5869, 0.3278]])
tensor([[1.7076, 1.6269, 1.9305],
        [0.9897, 0.5869, 0.3278]])


减法运算        
c = a - b       
c = torch.sub(a, b)     
a.sub(b)        
a.sub_(b)       

In [37]:
print(a - b)
print(a.sub(b))
print(torch.sub(a, b))
print(a)
print(a.sub_(b))

tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])
tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])
tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])
tensor([[0.9102, 0.8461, 0.9555],
        [0.7291, 0.0159, 0.0827]])
tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])


乘法运算        
+ 哈达玛积（element wise, 对应元素相乘）！注意与矩阵运算不同！      

c = a * b   
c = torch.mul(a, b)     
a.mul(b)        
a.mul_(b)       

In [38]:
print(a * b)
print(torch.mul(a, b))
print(a.mul(b))
print(a)
print(a.mul_(b))

tensor([[ 0.0899,  0.0511, -0.0191],
        [ 0.1221, -0.3168, -0.0398]])
tensor([[ 0.0899,  0.0511, -0.0191],
        [ 0.1221, -0.3168, -0.0398]])
tensor([[ 0.0899,  0.0511, -0.0191],
        [ 0.1221, -0.3168, -0.0398]])
tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])
tensor([[ 0.0899,  0.0511, -0.0191],
        [ 0.1221, -0.3168, -0.0398]])


除法运算        
c = a/b     
c = torch.div(a, b)     
a.div(b)        
a.div_(b)

In [39]:
print(a / b)
print(torch.div(a, b))
print(a.div(b))
print(a)
print(a.div_(b))

tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])
tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])
tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])
tensor([[ 0.0899,  0.0511, -0.0191],
        [ 0.1221, -0.3168, -0.0398]])
tensor([[ 0.1127,  0.0654, -0.0195],
        [ 0.4685, -0.5550, -0.1624]])


矩阵运算        
+ 二维矩阵乘法运算操作包括torch.mm()、torch.matmul()、@     

    a = torch.ones(2, 1)        
    b = torch.ones(1, 2)        
    print(torch.mm(a, b))       
    print(torch.matmul(a, b))       
    print(a @ b)        
    print(a.matmul(b))      
    print(a.mm(b))      


    a x b的矩阵必须要保证a是m乘n，b是n乘P   

+ 对于高维的Tensor(dim > 2)，定义其矩阵乘法仅在最后的两个维度上，       
要求前面的维度必须保持一致，就像矩阵的索引一样并且运算操只有torch.matmul()

    a = torch.ones(1, 2, 3, 4)      
    b = torch.ones(1, 2, 4, 4)      
    print(a.matmul(b))      
    print(torch.matmul(a, b))       

In [43]:
a = torch.ones(2, 1)        
b = torch.ones(1, 2)        
print(a)
print(b)
print("_______________")
print(a @ b)
print(a.matmul(b))
print(torch.matmul(a, b))
print(torch.mm(a, b))
print(a.mm(b))

tensor([[1.],
        [1.]])
tensor([[1., 1.]])
_______________
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [46]:
a = torch.ones(1, 2, 3, 4)
b = torch.ones(1, 2, 4, 3)


print(a.matmul(b))
print("**************************")
print(a.matmul(b).shape)

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
**************************
torch.Size([1, 2, 3, 3])


幂运算      

print(torch.pow(a, 2))      
print(a.pow(2))     
print(a**2)     
print(a.pow_(2))        

In [47]:
a = torch.tensor([1, 2])
print(torch.pow(a, 3))
print(a.pow(3))
print(a**3)
print(a.pow_(3))
print(a)

tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])


e的n次方

print(torch.exp(a))     
b = a.exp_()        

In [48]:
a = torch.tensor([1.0, 2.0])
print(torch.exp(a))
print(torch.exp_(a))
print(a.exp())
print(a.exp_())


tensor([2.7183, 7.3891])
tensor([2.7183, 7.3891])
tensor([  15.1543, 1618.1782])
tensor([  15.1543, 1618.1782])


开方运算        

print(a.sqrt())     
print(a.sqrt_())        
print(a)        

In [53]:
a = torch.tensor([10.0, 2.0])
print(a)
print(torch.sqrt(a))
print(torch.sqrt_(a))
print(a)
print(a.sqrt())
print(a.sqrt_())

tensor([10.,  2.])
tensor([3.1623, 1.4142])
tensor([3.1623, 1.4142])
tensor([3.1623, 1.4142])
tensor([1.7783, 1.1892])
tensor([1.7783, 1.1892])


对数运算        

print(torch.log2(a))        
print(torch.log10(a))       
print(torch.log(a))     
print(torch.log_(a))        

In [50]:
a = torch.tensor([10.0, 2.0])
print(torch.log(a))
print(torch.log_(a))
print(a.log())
print(a.log_())

tensor([2.3026, 0.6931])
tensor([2.3026, 0.6931])
tensor([ 0.8340, -0.3665])
tensor([ 0.8340, -0.3665])


### 03 Pytorch中的in-place操作

+ “就地”操作，即不允许使用临时变量。          
+ 也称为原位操作。        
+ x = x + y       
+ add_，sub_, mul_等等        

### 04 广播机制
+ 广播机制：张量参数可以自动扩展为相同大小（类似于Numpy)
+ 广播机制需要满足两个条件：
    - 每个张量至少有一个维度
    - 满足右对齐
    - torch.rand(2, 1, 1)+torch.rand(3)

In [54]:
import torch
a = torch.rand(2, 3)
b = torch.rand(3)

print(a)
print(b)
print(a + b)

tensor([[0.7817, 0.9514, 0.8736],
        [0.9672, 0.0618, 0.7672]])
tensor([0.8277, 0.1685, 0.9580])
tensor([[1.6094, 1.1199, 1.8316],
        [1.7949, 0.2303, 1.7253]])


05 取整和取余运算

In [55]:
import torch

a = torch.rand(2, 2)
a = a * 10
print(a)

print(torch.floor(a))
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))
print(torch.frac(a))
print(a % 2)


tensor([[6.8396, 7.6450],
        [2.3176, 8.1592]])
tensor([[6., 7.],
        [2., 8.]])
tensor([[7., 8.],
        [3., 9.]])
tensor([[7., 8.],
        [2., 8.]])
tensor([[6., 7.],
        [2., 8.]])
tensor([[0.8396, 0.6450],
        [0.3176, 0.1592]])
tensor([[0.8396, 1.6450],
        [0.3176, 0.1592]])


### 05 比较运算

torch.eq(input, other, out=None) # 按成员进行等式操作，相同返回True     
torch.equal(tensor1, tensor2) # 判断两个张量是否有相同的size 和 elements，则为True      
torch.ge(input, other, out=None) # 按成员进行大于等于操作，大于等于返回True     
torch.gt(input, other, out=None) # 按成员进行大于操作，大于返回True     
torch.le(input, other, out=None) # 按成员进行小于等于操作，小于等于返回True     
torch.lt(input, other, out=None) # 按成员进行小于操作，小于返回True     
torch.ne(input, other, out=None) # 按成员进行不等式操作，不相同返回True     




In [56]:
import torch

a = torch.rand(2, 3)
b = torch.rand(2, 3)


print(a)
print(b)

print(torch.eq(a, b))
print(torch.equal(a, b))
print(torch.ge(a, b))
print(torch.gt(a, b))
print(torch.le(a, b))
print(torch.lt(a, b))
print(torch.ne(a, b))



tensor([[0.9842, 0.8974, 0.9463],
        [0.8997, 0.9821, 0.0788]])
tensor([[0.9022, 0.4454, 0.6583],
        [0.7642, 0.7959, 0.1215]])
tensor([[False, False, False],
        [False, False, False]])
False
tensor([[ True,  True,  True],
        [ True,  True, False]])
tensor([[ True,  True,  True],
        [ True,  True, False]])
tensor([[False, False, False],
        [False, False,  True]])
tensor([[False, False, False],
        [False, False,  True]])
tensor([[True, True, True],
        [True, True, True]])


### 06 取前k大/前k小/第k小的数值及其索引

+ torch.sort(input, dim=None, descending = False, out=None) #对目标张量input沿着指定维按升序排序      
+ torch.topk(input, k, dim=None, largest=True, sorted=True, out=None) #沿着指定维度返回最大k个数值及其索引值      
    这个一般用在深度学习中对loss函数进行定义时候            
+ torch.kthvalue(input, k, dim=None, keepdim=False, out=None) #沿着指定维度返回第k个最小值及其索引值      

In [57]:
a = torch.tensor([1, 4, 4, 3, 5])
print(torch.sort(a))

torch.return_types.sort(
values=tensor([1, 3, 4, 4, 5]),
indices=tensor([0, 3, 1, 2, 4]))


In [61]:
a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
print(a.shape)
print(torch.sort(a, dim = 1, descending=True))

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[5, 4, 4, 3, 1],
        [5, 3, 3, 2, 1]]),
indices=tensor([[4, 1, 2, 3, 0],
        [4, 1, 3, 0, 2]]))


In [67]:
##topk
a = torch.tensor([[2, 4, 3, 1,5],
                  [2, 3, 5, 1, 4]])
print(a.shape)

print(torch.topk(a, k = 2, dim=0))
print(torch.topk(a, k = 1, dim=0))
print(torch.topk(a, k = 1, dim=1))
print(torch.topk(a, k = 2, dim=1))


torch.Size([2, 5])
torch.return_types.topk(
values=tensor([[2, 4, 5, 1, 5],
        [2, 3, 3, 1, 4]]),
indices=tensor([[0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1]]))
torch.return_types.topk(
values=tensor([[2, 4, 5, 1, 5]]),
indices=tensor([[0, 0, 1, 0, 0]]))
torch.return_types.topk(
values=tensor([[5],
        [5]]),
indices=tensor([[4],
        [2]]))
torch.return_types.topk(
values=tensor([[5, 4],
        [5, 4]]),
indices=tensor([[4, 1],
        [2, 4]]))


In [69]:
print(torch.kthvalue(a, k = 2, dim=0))
print(torch.kthvalue(a, k = 2, dim=1))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))
torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


### 07 判断是否为finite/inf/nan

+ torch.isfinite(tensor)/torch.isinf(tensor)/torch.isnan(tensor)      
+ 返回一个标记元素是否为finite/inf/nan的mask张量      

In [70]:
a = torch.rand(2, 3)

print(a)
print(a/0)
print(torch.isfinite(a))
print(torch.isfinite(a/0))
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[0.9711, 0.0940, 0.8417],
        [0.2347, 0.8983, 0.8136]])
tensor([[inf, inf, inf],
        [inf, inf, inf]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [71]:
import numpy as np

a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))
print(torch.isinf(a))


tensor([False, False,  True])
tensor([False, False, False])


### 08 三角函数

torch.abs(input, out=None)      
torch.acos(input, out=None)     
torch.asin(input, out=None)     
torch.atan(input, out=None)     
torch.atan2(input1, input2, out=None)       
torch.cos(input, out=None)      
torch.cosh(input, out=None)     
torch.sin(input, out=None)      
torch.sinh(input, out=None)     
torch.tan(input, out=None)      
torch.tanh(input, out=None)     


In [73]:
import torch
a = torch.rand(2, 3)
print(a)
b = torch.cos(a)
print(b)

tensor([[0.1356, 0.2106, 0.3665],
        [0.1437, 0.0881, 0.8351]])
tensor([[0.9908, 0.9779, 0.9336],
        [0.9897, 0.9961, 0.6711]])


### 09 其它的数学函数

torch.asb()     
torch.erf()     
torch.erfinv()      
torch.sigmoid()     
torch.neg()     
torch.reciprocal()      
torch.rsqrt()       
torch.sign()        
torch.lerp()        
torch.addcdiv()     
torch.addcmul()     
torch.cumprod()     
torch.cumsum()      

### 10 统计学有关的函数

torch.mean()   #平均值      
torch.sum()    #求和            
torch.prod()   #求积            
torch.max()    #最大值      
torch.min()    #最小值      
torch.argmax() #最大值索引      
torch.argmin() #最小值索引      


torch.median() #中位数      
torch.std()    #标准差      
torch.var()    #方差        
torch.mode()   #众数        
torch.histc()  #直方图统计      
torch.bincount() #计数      

In [75]:
import torch

a = torch.rand(2, 2)

print(a)
print(torch.mean(a))
print(torch.sum(a))
print(torch.prod(a))
print(torch.std(a))
print(torch.var(a))
print(torch.median(a))
print(torch.mode(a))
print(torch.norm(a))
print(torch.dist(a, a))
print(torch.histc(a))

tensor([[0.7180, 0.2160],
        [0.5633, 0.5754]])
tensor(0.5182)
tensor(2.0727)
tensor(0.0503)
tensor(0.2134)
tensor(0.0455)
tensor(0.5633)
torch.return_types.mode(
values=tensor([0.2160, 0.5633]),
indices=tensor([1, 0]))
tensor(1.1003)
tensor(0.)
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])


In [76]:
a = torch.rand(2, 2) * 10
print(a)

print(torch.histc(a, bins=4, min=0, max=10))

tensor([[3.1165, 4.2924],
        [2.8380, 5.6892]])
tensor([0., 3., 1., 0.])


### 11 分布函数torch.distributions

如机器学习中的训练集和测试集的分布是否一致      

- distributions包含可参数化的概率分布和采样函数             
    - 得分函数           
         - 强化学习中策略梯度方法的基础               
    - pathwise derivative估计器       
        - 变分自动编码器中的重新参数化技巧        

### 12 随机抽样函数

- 定义随机种子          
    - torch.manual_seed(seed)       
- 定义随机满足的分布        
    - torch.normal()

In [81]:
import torch

torch.manual_seed(42)
mean = torch.rand(1, 2)
std  = torch.rand(1, 2)

print(torch.normal(mean, std))

tensor([[0.9720, 1.1360]])


- 范数
    - 在泛函分析中，它定义在赋范线性空间中，并满足一定的条件，即1.非负性；2齐次性；3.三角不等式
    - 常被用来度量某个向量空间（或矩阵）中的每个向量的长度或大小

- 0范数/1范数/2范数/p范数/核范数
    - torch.dist(input, other, p=2)计算p范数
    - torch.norm() 计算2范数

### 补：向量与矩阵的范数

范数（Norm）是一个数学概念，表示向量或矩阵的“大小”或“长度”，        
它是衡量向量或矩阵在空间中某种距离的方式。在数学、物理学和计算机科学中，        
范数常用于优化、距离计算、机器学习和信号处理等领域。

以下是几种常见的范数：0范数、1范数、2范数、p范数、核范数，      
它们通常用于向量和矩阵的计算中，不同的范数具有不同的特性和应用。        

---

#### 1. 0 范数（零范数，L0 Norm）       
**定义**：零范数并不是真正的范数，但它常常被用来计算一个向量或矩阵中非零元素的个数。        
用公式表示为：      
$ \|x\|_0 = \text{非零元素的个数} $

**性质**：
- 零范数不是严格意义上的范数，因为它不满足**齐次性**（例如，$ \| \alpha x \|_0 \neq \alpha \| x \|_0 $，对于标量 $ \alpha $）。
- 但是，零范数通常用于**稀疏性**相关的任务中，比如 **LASSO回归**、**特征选择**等。

**应用**：
- **稀疏表示**：通过零范数可以衡量一个向量或矩阵有多少个非零元素。      
在机器学习中，通常希望得到一个具有较少非零元素的模型，这样的模型更加稀疏、简单、易于解释。      
- **特征选择**：通过零范数来选出最重要的特征，抑制不重要的特征。

---

#### 2. 1 范数（L1 Norm）
**定义**：1范数是向量中所有元素绝对值的和，公式如下：
$ \|x\|_1 = \sum_i |x_i| $

**性质**：
- L1 范数会使得一些元素变为 0，因此常用于实现**稀疏化**。
- 它对于噪声较敏感，但能够很好地处理**稀疏问题**。

**应用**：
- **LASSO回归**：L1范数用于正则化（惩罚模型的复杂度），     
通过约束模型参数的 L1 范数来使得一些系数变为 0，从而选择重要特征。      
- **稀疏编码和压缩感知**：L1范数用于找到稀疏表示，减少数据的冗余。      
  
---

#### 3. 2 范数（L2 Norm）
**定义**：2范数，也称为 **欧几里得范数**，是向量各元素的平方和的平方根，公式如下：
$ \|x\|_2 = \sqrt{\sum_i x_i^2} $

**性质**：
- L2 范数与欧几里得距离相关，常用于计算两点之间的距离。
- L2 范数的优点是其具有**平滑性**，不会导致像 L1 范数那样产生稀疏解。
- L2 范数对于异常值更为**鲁棒**，相比 L1 范数，它的计算结果更为平滑。

**应用**：
- **Ridge回归**：L2范数用于正则化，通过约束参数的L2范数来控制模型的复杂度，避免过拟合。
- **梯度下降算法**：L2范数常用于优化问题中，特别是当我们需要最小化误差平方和时。

---

#### 4. p 范数（Lp Norm）
**定义**：p范数是对任意 $p \geq 1$ 的扩展，公式如下：
$ \|x\|_p = \left( \sum_i |x_i|^p \right)^{1/p} $       
当 $p = 1$ 时，得到的是 **L1范数**，当 $p = 2$ 时，得到的是 **L2范数**，        
当 $p \to \infty$ 时，得到的是 **最大值范数**（即最大元素的绝对值）。       

**性质**：
- 当 $p = 1$，是 L1 范数；
- 当 $p = 2$，是 L2 范数；
- 随着 $p$ 增加，p 范数变得对大元素更敏感，尤其是 $p$ 较大时，p 范数更加注重向量中最大元素的影响。

**应用**：
- **正则化**：p范数的正则化（例如，L1正则化和L2正则化）用于约束模型的参数，防止过拟合。
- **最优解的选择**：在机器学习中，根据问题需要选择不同的 p 范数进行优化，p 范数适用于不同的平滑性需求。

---

#### 5. 核范数（Nuclear Norm）
**定义**：核范数是一个矩阵的所有奇异值的和，也可以理解为矩阵的 **L1 范数** 对奇异值的扩展。     
对于矩阵 $X$，其核范数定义为：      
$ \|X\|_* = \sum_i \sigma_i $       
其中 $ \sigma_i $ 是矩阵 $X$ 的奇异值。     

**性质**：
- 核范数广泛用于矩阵补全问题中，能够得到**低秩矩阵**。
- 核范数与 **L1 范数** 类似，但它作用于矩阵的奇异值，而不是矩阵元素本身。
  
**应用**：
- **矩阵补全**：在缺失数据的情况下，使用核范数来逼近低秩矩阵，常用于推荐系统（如Netflix的电影推荐）。
- **低秩矩阵恢复**：核范数正则化能够找到矩阵的低秩近似，广泛应用于图像去噪、信号恢复、协同过滤等领域。

---

#### 总结

| **范数**   | **定义**                                         | **性质**                                         | **常见应用**                                           |
|------------|--------------------------------------------------|--------------------------------------------------|--------------------------------------------------------|
| **0范数**  | 非零元素的个数                                   | 不满足常规范数条件，常用于稀疏性                  | 特征选择，稀疏编码                                    |
| **1范数**  | 向量元素绝对值之和                               | 对稀疏性友好，可使部分元素为零                    | LASSO回归，稀疏编码，压缩感知                        |
| **2范数**  | 向量元素平方和的平方根                           | 对异常值更为鲁棒，平滑                            | Ridge回归，机器学习中的常见损失函数，距离计算        |
| **p范数**  | 向量元素绝对值的p次方和的p次方根                 | 对大元素更敏感，p越大对极值越敏感                 | 最优化问题，正则化，调整平滑性                        |
| **核范数** | 矩阵奇异值的和                                   | 用于低秩矩阵恢复，矩阵补全                        | 矩阵补全，推荐系统，低秩矩阵恢复                      |

这些范数在 **机器学习、深度学习、信号处理** 和 **图像处理** 等多个领域有着广泛的应用，能够帮助我们在优化模型时控制参数的大小或稀疏性，解决实际问题中的多种挑战。


In [84]:
import torch

a = torch.rand(2, 1)
b = torch.rand(2, 1)

print(a, b)
print(torch.dist(a, b, p = 1 ))
print(torch.dist(a, b, p = 2 ))
print(torch.dist(a, b, p = 3 ))


print(torch.norm(a))

tensor([[0.7411],
        [0.4294]]) tensor([[0.8854],
        [0.5739]])
tensor(0.2888)
tensor(0.2042)
tensor(0.1820)
tensor(0.8565)


# 022 to learn